### ISSUE TITLE
Tap GestureRecognizer not working for Android platform

### ISSUE THREAD

**Issue by jmesh** [jamesmontemagno/Xamarin.Forms-Monkeys#14]
Works fine for iOS. Click and it works great for my image carousel, but in Android, the event is not raised at all. Haven't tested in UWP. 

On another note, adding functionality like a slide timer or move to next image would be very helpful for those who want to customize more than just a basic image carousel for Xamarin Forms.

**Comment by jmesh** [comment]
Was able to workaround this issue by actually adding the tap GestureRecognizer to the nested image in the XAML control versus using the actual control itself.

**Comment by castrojr913** [comment]
@jmesh Dear, What's is the fix for this issue? Can you share some code?
