### ISSUE TITLE
Problem after migrating to Xamarin.Forms 1.3

### ISSUE THREAD

**Issue by tkowalczyk** [jamesmontemagno/Xamarin.Forms-Monkeys#4]
![screen shot 2015-01-26 at 22 26 10](https://cloud.githubusercontent.com/assets/1682564/5908739/859a8d1c-a5aa-11e4-9cec-0d3df1e26bd9.png)

**Comment by jamesmontemagno** [comment]
Updated all the projects to newer versions.
